### PR TITLE
Install boshv2 instead of boshv1

### PR DESCRIPTION
**Pull request by bodymindarts**
Fixes https://github.com/starkandwayne/jumpbox/issues/23

### CODE REVIEW

**Comment by jhunt** [comment]
There are still people in the world using bosh-init and the Ruby bosh CLI

**Comment by bodymindarts** [comment]
Can't they pin the version of the jumpbox script to one that contains boshv1... or install it manually via `gem install`?

**Comment by jhunt** [comment]
They can.  We could also install both, instead of just the latest.  IIRC, Genesis can handle the new CLI being called `bosh2`

**Comment by bodymindarts** [comment]
In that case that is probably best

**Comment by bodymindarts** [comment]
@jhunt updated PR

**Comment by jhunt** [comment]
Thanks! :+1:

**Pull request merged**
